### ISSUE TITLE
First install failure - Update README

### ISSUE THREAD

**Issue by AmurgCodru** [cooper/quiki#99]
HI

`go get github.com/cooper/quiki` issues the following error:
```bash
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

Thus correct would be  `go install github.com/cooper/quiki@latest`

However, when running the wiki we get the error mentioned in https://github.com/cooper/quiki/issues/97
quiki quiki.conf
```
2024/12/21 17:04:22 [refs/heads/master] <nil>
2024/12/21 17:04:22 [default] template registered: /tmpl/default/
2024/12/21 17:04:22 [mywiki] pages will be handled at wiki root: /
2024/12/21 17:04:22 [mywiki] registered image root: /image/
2024/12/21 17:04:22 [mywiki] registered category root: /topic/
2024/12/21 17:04:22 [mywiki] registered file root: /file/ (...)
2024/12/21 17:04:22 setup static: stat : no such file or directory
```

### Cloning issue

Git cloning this repo will result in some errors the fact that pikaday and ace are not recursively cloned and thus ace.js is missing and gives an error in the browser(after extensive searching I noticed the folders empty)

To solve this one must manually do:
` git submodule update --init --recursive`

Then rebuilding and running with LOCAL binary
```
go build
./quiki quiki.conf
```

This eventually works but feels clunky to get started with, maybe update the readme?:)

**Comment by cooper** [comment]
yeah, thanks for pointing out the workaround. I agree the process (and readme) needs updated. It was written pre- go modules back when `go get` would clone it recursively to within your GOPATH. Then all you'd have to do is edit the config to point to `$GOPATH/github.com/cooper/quiki`. Probably could have derived it from the environment, thinking back, but didn't.

Anyway, that is no longer relevant since quiki is now shipped as a module, so I am working on modernizing this project. I think the goal is that it's functional after `go install` and little/no configuration. I just made a change to embed the static resources in the binary so that it no longer depends on the repository existing on the filesystem. next will be the README!
